
-- +migrate Up
CREATE TABLE IF NOT EXISTS statuses(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    name VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- +migrate Down
